baseURL = 'https://hyperagon.github.io/'
languageCode = 'en-us'
title = 'Hyperagon'
theme = 'PaperMod'

[params]
env = "production"
title = "Magic"
description = "Programmer by Day, Wizard by Night"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Hyperagon"

  [params.contact]
    email = 'vimino•net@gmail•com'

